### ISSUE TITLE
Autoprefixing missing sample

### ISSUE THREAD

**Issue by IngenieroLata** [survivejs/webpack-book#297]
I found something weird that makes me confuse with *. browserslistrc* intention, in the chapter **7. Autoprefixing** shows this sample code being added to `main.css`:
```
.pure-button {
  border-radius: 1em;
}
```

But after setting up the *postcss-loader* with *autoprefixer* shows this sample code:
```
.pure-button {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}
```

For a moment I though the *.browserslistrc* made some sort of wrapping rules to add support for borders along with flex-box, then I realize the first sample was intended to be: 

```
.pure-button {
  display: flex;
}
```

or maybe am I missing something?

**Comment by bebraw** [comment]
Hi,

It's my mistake. I forgot to update that code while revising. Fixes next
week.

On Mar 3, 2018 18:35, "Diego Toro" <notifications@github.com> wrote:

I found something weird that makes me confuse with *. browserslistrc*
intention, in the chapter *7. Autoprefixing* shows this sample code being
added to main.css:

.pure-button {
  border-radius: 1em;
}

But after setting up the *postcss-loader* with *autoprefixer* shows this
sample code:

.pure-button {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}

For a moment I though the *.browserslistrc* made some sort of wrapping
rules to add support for borders along with flex-box, then I realize the
first sample was intended to be:

.pure-button {
  display: flex;
}

or maybe am I missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/survivejs/webpack-book/issues/297>, or mute the thread

**Comment by IngenieroLata** [comment]
Awesome! thanks

**Comment by bebraw** [comment]
Done in 510f75c90.
